name: Trigger on main branch to exp and prod envs

on:
  push:
    branches:
    - main

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure ML job
      run: |
        az ml job create --file src/job_dev.yml -g peeush.agarwal-rg -w mlops-learn-ws
  production:
    runs-on: ubuntu-latest
    environment: Production
    needs: experiment
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure ML job
      run: |
        az ml job create --file src/job_prod.yml -g peeush.agarwal-rg -w mlops-learn-ws
